'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useSession } from 'next-auth/react'
import { CmsShell } from '@/components/cms-shell'
import { ErrorBanner, Spinner } from '@/components/feedback'

type Account = { id: string; name: string; email: string | null; phone: string | null; role: string | null; accountType: string; status: string; address: string | null; createdAt: string; phoneVerifiedAt: string | null; emailVerifiedAt: string | null; verifiedById: string | null }
const statusLabel: Record<string, string> = { MENUNGGU_VERIFIKASI: 'Menunggu verifikasi', AKTIF: 'Aktif', NONAKTIF: 'Nonaktif' }

export default function CmsAccountDetailPage() {
  const { data: session } = useSession(); const params = useParams<{ id: string }>(); const [account, setAccount] = useState<Account | null>(null); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  async function load() { const response = await fetch(`/api/admin/accounts/${params.id}`); const result = await response.json(); if (!response.ok) setError(result.error ?? 'Gagal memuat detail akun.'); else setAccount(result.data) }
  useEffect(() => { if (params.id) void load() }, [params.id])
  async function verify() { setBusy(true); setError(''); const response = await fetch(`/api/admin/accounts/${params.id}/verify`, { method: 'POST' }); const result = await response.json(); if (!response.ok) setError(result.error ?? 'Verifikasi gagal.'); else { setMessage('Akun berhasil diverifikasi.'); await load() }; setBusy(false) }
  async function changeStatus(status: 'AKTIF' | 'NONAKTIF') { setBusy(true); setError(''); const response = await fetch(`/api/admin/accounts/${params.id}/status`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); const result = await response.json(); if (!response.ok) setError(result.error ?? 'Perubahan status gagal.'); else { setMessage('Status akun berhasil diperbarui.'); await load() }; setBusy(false) }
  if (!account) return <CmsShell session={session ?? null} active="/cms/accounts" title="Detail akun warga"><Spinner />{error ? <ErrorBanner message={error} /> : null}</CmsShell>
  const initials = account.name.split(' ').map(part => part[0]).slice(0, 2).join('').toUpperCase()
  return <CmsShell session={session ?? null} active="/cms/accounts" title="Detail akun warga" actions={<span className={`rounded-full px-4 py-2 text-xs font-bold ${account.status === 'AKTIF' ? 'bg-[#E8F8F0] text-[#16875A]' : 'bg-[#FFF2D9] text-[#B77A00]'}`}>{statusLabel[account.status]}</span>}>
    <p className="mb-5 text-[11px] font-semibold text-[#5B4BFF]"><Link href="/cms/accounts">Manajemen akun</Link> / {account.name}</p>
    <div className="grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="min-h-[560px] rounded-3xl bg-[#0B102F] p-6 text-white"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[#6D63FF] text-xl font-bold">{initials}</div><h2 className="mt-5 text-center text-xl font-bold">{account.name}</h2><p className="mt-2 text-center text-xs text-[#C3C6D4]">{account.accountType === 'WARGA' ? 'Warga' : 'Pengurus'} · RW 08</p><div className="mt-8 space-y-4 text-xs"><p className="border-b border-[#292E4A] pb-4">☎ &nbsp;{account.phone || 'Nomor HP belum tersedia'}</p><p className="border-b border-[#292E4A] pb-4">✉ &nbsp;{account.email || 'Email belum tersedia'}</p><p className="border-b border-[#292E4A] pb-4">▣ &nbsp;Dibuat {new Date(account.createdAt).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' })}</p></div></aside><section className="rounded-3xl border-2 border-[#62A9E8] bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Data verifikasi</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Info label="Nama lengkap" value={account.name} /><Info label="Email" value={account.email} /><Info label="Nomor HP" value={account.phone} /><Info label="Tipe akun" value={account.accountType === 'WARGA' ? 'Warga' : 'Pengurus'} /><Info label="Alamat" value={account.address} /><Info label="Role" value={account.role || 'Warga'} /></div><div className="mt-5 rounded-2xl border border-dashed border-slate-300 p-5"><p className="font-bold">Dokumen verifikasi</p><p className="mt-2 text-xs text-[#6F7385]">Dokumen identitas belum tersedia pada data akun ini.</p></div>{error ? <div className="mt-4"><ErrorBanner message={error} /></div> : null}{message ? <p className="mt-4 text-sm text-emerald-700">{message}</p> : null}<div className="mt-5 flex flex-wrap justify-end gap-2">{account.status === 'MENUNGGU_VERIFIKASI' ? <><button disabled={busy} onClick={() => changeStatus('NONAKTIF')} className="rounded-full border border-red-200 px-4 py-2 text-xs font-bold text-red-700">Tolak verifikasi</button><button disabled={busy} onClick={() => verify()} className="rounded-full bg-[#5B4BFF] px-5 py-2 text-xs font-bold text-white">Verifikasi akun</button></> : account.status === 'AKTIF' ? <button disabled={busy} onClick={() => changeStatus('NONAKTIF')} className="rounded-full border border-red-200 px-4 py-2 text-xs font-bold text-red-700">Nonaktifkan akun</button> : <button disabled={busy} onClick={() => changeStatus('AKTIF')} className="rounded-full bg-[#5B4BFF] px-5 py-2 text-xs font-bold text-white">Aktifkan akun</button>}</div></section></div>
  </CmsShell>
}
function Info({ label, value }: { label: string; value: string | null }) { return <label className="text-[11px] font-semibold text-[#6F7385]">{label}<div className="mt-2 rounded-xl border border-slate-200 bg-[#FAFAFC] px-4 py-3 text-sm font-normal text-[#111322]">{value || 'Belum tersedia'}</div></label> }
