import Link from 'next/link'
import type { ReactNode } from 'react'

export function CitizenShell({ children, active, title, eyebrow = 'LAYANAN WARGA', subtitle }: { children: ReactNode; active: string; title: string; eyebrow?: string; subtitle?: string }) {
  const links = [['/dashboard', 'Beranda'], ['/informasi', 'Informasi'], ['/finance/reports', 'Keuangan'], ['/reports', 'Laporan Saya'], ['/reports/sick', 'Laporan Sakit']]
  return <main className="min-h-screen bg-[#F5F6FA] text-[#111322]"><header className="sticky top-0 z-10 flex min-h-[76px] flex-wrap items-center justify-between gap-x-5 gap-y-3 border-b border-[#E7E8EF] bg-white px-5 py-4 sm:px-10 lg:flex-nowrap lg:px-14"><Link href="/dashboard" className="flex shrink-0 items-center gap-3"><span className="flex h-[34px] w-[34px] items-center justify-center rounded-[9px] bg-[#5B4BFF] text-xs font-extrabold text-white">RW</span><span className="text-[17px] font-bold">Portal Warga</span></Link><nav className="order-3 flex w-full items-center gap-5 overflow-x-auto whitespace-nowrap text-[12px] font-medium text-[#6F7385] lg:order-none lg:w-auto lg:gap-7 lg:text-[13px]">{links.map(([href, label]) => <Link key={href} className={active === href ? 'font-bold text-[#5B4BFF]' : ''} href={href}>{label}</Link>)}</nav><Link href="/dashboard" className="flex h-9 w-9 items-center justify-center rounded-full bg-[#D9D5FF] text-sm font-bold text-[#3728D6]">W</Link></header><div className="mx-auto max-w-[1328px] px-5 py-7 sm:px-10 lg:px-14"><div className="mb-6"><p className="text-[11px] font-bold tracking-[1.5px] text-[#5B4BFF]">{eyebrow}</p><h1 className="mt-2 text-3xl font-bold sm:text-[34px]">{title}</h1>{subtitle ? <p className="mt-2 max-w-2xl text-sm text-[#6F7385]">{subtitle}</p> : null}</div>{children}</div></main>
}

export function CitizenLoginRequired() { return <main className="flex min-h-screen items-center justify-center bg-[#F5F6FA] px-5"><section className="w-full max-w-md rounded-[22px] bg-white p-8 text-center shadow-sm"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#EFEDFF] text-2xl text-[#5B4BFF]">↗</div><h1 className="mt-5 text-2xl font-bold">Silakan login dulu</h1><p className="mt-3 text-sm leading-6 text-[#6F7385]">Halaman ini hanya untuk warga yang sudah login.</p><Link href="/" className="mt-6 inline-flex h-12 w-full items-center justify-center rounded-full bg-[#5B4BFF] text-sm font-bold text-white">Ke halaman login</Link></section></main> }
