import Link from 'next/link'
import { redirect } from 'next/navigation'
import { auth } from '@/auth'
import { prisma } from '@/lib/db'

const statusLabels: Record<string, string> = { TERKIRIM: 'Terkirim', DITINJAU: 'Sedang ditinjau', DIPROSES: 'Sedang diproses', SELESAI: 'Selesai', TIDAK_DAPAT_DIPROSES: 'Tidak dapat diproses' }
const monthFormatter = new Intl.DateTimeFormat('id-ID', { month: 'short' })
const currency = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 })

export default async function DashboardPage() {
  const session = await auth()
  if (!session?.user) redirect('/')
  if (session.user.status !== 'AKTIF') return <PendingVerification />
  if (session.user.accountType === 'PENGURUS') redirect('/cms/content')

  const [contents, agendas, programs, documentation, financeReports, citizenReports, sicknessReports, recentReports] = await Promise.all([
    prisma.content.findMany({ where: { status: 'PUBLISHED' }, orderBy: { publishedAt: 'desc' }, take: 4 }),
    prisma.agenda.findMany({ where: { status: 'PUBLISHED', startsAt: { gte: new Date() } }, orderBy: { startsAt: 'asc' }, take: 4 }),
    prisma.programUpdate.findMany({ where: { status: 'PUBLISHED' }, orderBy: { createdAt: 'desc' }, take: 4 }),
    prisma.documentation.findMany({ where: { status: 'PUBLISHED' }, orderBy: { createdAt: 'desc' }, take: 4 }),
    prisma.financeReport.findMany({ where: { status: 'DIPUBLIKASIKAN' }, orderBy: { periodStart: 'desc' }, take: 3 }),
    prisma.citizenReport.count({ where: { reporterId: session.user.id } }),
    prisma.sicknessReport.count({ where: { reporterId: session.user.id } }),
    prisma.citizenReport.findMany({ where: { reporterId: session.user.id }, orderBy: { createdAt: 'desc' }, take: 3, select: { id: true, title: true, status: true, createdAt: true } }),
  ])

  const latestFinance = financeReports[0]
  const transactions = latestFinance ? await prisma.financeTransaction.findMany({ where: { occurredAt: { gte: latestFinance.periodStart, lte: latestFinance.periodEnd } }, select: { type: true, amount: true, occurredAt: true }, orderBy: { occurredAt: 'asc' } }) : []
  const financeSeries = buildFinanceSeries(transactions, latestFinance?.periodStart, latestFinance?.periodEnd)
  const totalIncome = transactions.filter(item => item.type === 'PEMASUKAN').reduce((sum, item) => sum + Number(item.amount), 0)
  const totalExpense = transactions.filter(item => item.type === 'PENGELUARAN').reduce((sum, item) => sum + Number(item.amount), 0)
  const userName = session.user.name?.split(' ')[0] || 'Warga'

  return <main className="min-h-screen bg-[#F5F6FA] text-[#111322]">
    <Header name={session.user.name ?? 'Warga'} />
    <div className="mx-auto flex max-w-[1328px] flex-col gap-6 px-5 py-7 sm:px-10 lg:px-14">
      <section className="flex min-h-[218px] items-center justify-between overflow-hidden rounded-[22px] bg-gradient-to-r from-[#3225C9] to-[#5B4BFF] px-7 py-8 text-white sm:px-10"><div><p className="text-[11px] font-bold tracking-[1.6px] text-[#D8D4FF]">SELAMAT DATANG KEMBALI</p><h1 className="mt-3 text-3xl font-bold sm:text-[34px]">Halo, {userName}! Apa kabar hari ini?</h1><p className="mt-3 max-w-[610px] text-sm leading-6 text-[#E5E2FF]">Ringkasan informasi, kegiatan, keuangan, dan layanan RW 08 ada di sini.</p><Link href="/reports" className="mt-5 inline-flex h-11 items-center rounded-full bg-white px-[18px] text-[13px] font-bold text-[#3728D6]">＋&nbsp; Buat laporan</Link></div><div className="hidden text-[100px] opacity-20 lg:block">⌂</div></section>
      <section className="grid grid-cols-2 gap-4 lg:grid-cols-4"><Metric label="Laporan saya" value={citizenReports} color="text-[#5B4BFF]" /><Metric label="Laporan sakit" value={sicknessReports} color="text-[#E25555]" /><Metric label="Agenda mendatang" value={agendas.length} color="text-[#F4A340]" /><Metric label="Laporan keuangan" value={financeReports.length} color="text-[#16A36A]" /></section>
      <section className="grid gap-6 lg:grid-cols-[1.35fr_0.65fr]"><div className="rounded-[18px] bg-white p-6"><SectionHeader title="Kegiatan mendatang" link="/informasi" linkLabel="Lihat semua" />{!agendas.length?<Empty title="Belum ada kegiatan mendatang" text="Agenda yang akan datang dari pengurus akan tampil di sini."/>:<div className="mt-4 space-y-3">{agendas.map(agenda=><article key={agenda.id} className="flex gap-4 rounded-2xl border border-[#E7E8EF] p-4"><div className="flex h-14 w-14 shrink-0 flex-col items-center justify-center rounded-xl bg-[#EFEDFF] text-[#5B4BFF]"><strong className="text-xl leading-5">{new Date(agenda.startsAt).getDate()}</strong><span className="text-[10px] font-bold uppercase">{monthFormatter.format(new Date(agenda.startsAt))}</span></div><div><p className="text-[10px] font-bold tracking-[1px] text-[#5B4BFF]">{new Date(agenda.startsAt).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})} · {agenda.location ?? 'Lokasi diumumkan'}</p><h3 className="mt-1 font-bold">{agenda.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#6F7385]">{agenda.description}</p></div></article>)}</div>}</div><div className="rounded-[18px] bg-[#0B102F] p-6 text-white"><p className="text-[10px] font-bold tracking-[1.3px] text-[#AAA5FF]">AGENDA TERDEKAT</p>{agendas[0]?<><p className="mt-4 text-5xl font-bold">{new Date(agendas[0].startsAt).getDate()}</p><p className="mt-1 text-xs text-[#C7C9D6]">{new Date(agendas[0].startsAt).toLocaleDateString('id-ID',{month:'long',year:'numeric'})}</p><h3 className="mt-5 font-bold">{agendas[0].title}</h3><p className="mt-2 text-xs text-[#C7C9D6]">{agendas[0].location ?? 'Lokasi menyusul'}</p></>:<p className="mt-5 text-sm text-[#C7C9D6]">Belum ada agenda mendatang.</p>}</div></section>
      <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-[18px] bg-white p-6"><SectionHeader title="Program & perkembangan" link="/informasi" linkLabel="Lihat semua" />{!programs.length?<Empty title="Belum ada perkembangan program" text="Update program RW yang sudah atau sedang berjalan akan tampil di sini."/>:<div className="mt-4 space-y-3">{programs.map(program=><article key={program.id} className="border-b border-[#E7E8EF] pb-3 last:border-0"><p className="text-[10px] font-bold tracking-[1px] text-[#5B4BFF]">PERKEMBANGAN PROGRAM</p><h3 className="mt-1 text-sm font-bold">{program.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#6F7385]">{program.body}</p></article>)}</div>}</div><div className="rounded-[18px] bg-white p-6"><SectionHeader title="Dokumentasi kegiatan" link="/informasi" linkLabel="Lihat semua" />{!documentation.length?<Empty title="Belum ada dokumentasi" text="Dokumentasi kegiatan RW akan tampil setelah dipublikasikan."/>:<div className="mt-4 grid grid-cols-2 gap-3">{documentation.map(item=><article key={item.id} className="rounded-xl border border-[#E7E8EF] p-3"><div className="flex h-20 items-center justify-center rounded-lg bg-gradient-to-br from-[#EFEDFF] to-[#D9D5FF] text-2xl text-[#5B4BFF]">▧</div><h3 className="mt-2 line-clamp-2 text-xs font-bold">{item.title}</h3><p className="mt-1 line-clamp-2 text-[11px] text-[#6F7385]">{item.description ?? 'Dokumentasi kegiatan RW 08'}</p></article>)}</div>}</div></section>
      <section className="grid gap-6 lg:grid-cols-[1.25fr_0.75fr]"><div className="rounded-[18px] bg-white p-6"><SectionHeader title="Grafik laporan keuangan" link="/finance/reports" linkLabel="Buka laporan" />{latestFinance?<><p className="mt-1 text-xs text-[#6F7385]">Periode {latestFinance.periodStart.toLocaleDateString('id-ID')} – {latestFinance.periodEnd.toLocaleDateString('id-ID')}</p><FinanceChart series={financeSeries}/><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#E8F8F0] p-3"><p className="text-[11px] text-[#16875A]">Total pemasukan</p><p className="mt-1 text-sm font-bold text-[#16875A]">{currency.format(totalIncome)}</p></div><div className="rounded-xl bg-[#FFF0F0] p-3"><p className="text-[11px] text-[#B53B3B]">Total pengeluaran</p><p className="mt-1 text-sm font-bold text-[#B53B3B]">{currency.format(totalExpense)}</p></div></div></>:<Empty title="Belum ada laporan keuangan" text="Grafik akan tampil setelah laporan keuangan dipublikasikan."/>}</div><div className="rounded-[18px] bg-white p-6"><SectionHeader title="Informasi terbaru" link="/informasi" linkLabel="Lihat semua" />{!contents.length?<Empty title="Belum ada informasi" text="Berita dan pengumuman RW akan tampil di sini."/>:<div className="mt-3 divide-y divide-[#E7E8EF]">{contents.map(content=><article key={content.id} className="py-3"><p className="text-[10px] font-bold tracking-[1px] text-[#5B4BFF]">{content.type}</p><h3 className="mt-1 text-sm font-bold">{content.title}</h3><p className="mt-1 line-clamp-2 text-[11px] leading-5 text-[#6F7385]">{content.body}</p></article>)}</div>}</div></section>
      <section className="grid gap-6 lg:grid-cols-[1fr_330px]"><div className="rounded-[18px] bg-white p-6"><SectionHeader title="Status laporan saya" link="/reports" linkLabel="Kelola laporan" />{!recentReports.length?<Empty title="Belum ada laporan" text="Laporan yang kamu kirim akan muncul di sini."/>:<div className="mt-4 space-y-3">{recentReports.map(report=><div key={report.id} className="flex items-center justify-between gap-3 rounded-xl border border-[#E7E8EF] p-3"><div><p className="text-sm font-bold">{report.title}</p><p className="mt-1 text-[11px] text-[#8D91A1]">{new Date(report.createdAt).toLocaleDateString('id-ID')}</p></div><span className="rounded-full bg-[#EFEDFF] px-3 py-1 text-[10px] font-bold text-[#3728D6]">{statusLabels[report.status] ?? report.status}</span></div>)}</div>}</div><div className="rounded-[18px] bg-white p-[22px]"><h2 className="text-base font-bold">Akses cepat</h2><div className="mt-3 space-y-1"><Quick href="/finance/reports" icon="▣" label="Lihat laporan keuangan"/><Quick href="/reports" icon="▤" label="Buat laporan warga"/><Quick href="/reports/sick" icon="♡" label="Laporkan warga sakit"/></div></div></section>
    </div>
  </main>
}

function buildFinanceSeries(transactions: { type: string; amount: { toNumber?: () => number } | number; occurredAt: Date }[], start?: Date, end?: Date) { if (!start || !end) return []; const series = new Map<string,{label:string; income:number; expense:number}>(); const cursor = new Date(start); cursor.setDate(1); while(cursor <= end){const key=`${cursor.getFullYear()}-${cursor.getMonth()}`;series.set(key,{label:monthFormatter.format(cursor),income:0,expense:0});cursor.setMonth(cursor.getMonth()+1)} transactions.forEach(item=>{const key=`${item.occurredAt.getFullYear()}-${item.occurredAt.getMonth()}`;const bucket=series.get(key);if(bucket){const amount=typeof item.amount==='number'?item.amount:item.amount.toNumber?.()??Number(item.amount);if(item.type==='PEMASUKAN')bucket.income+=amount;else bucket.expense+=amount}});return Array.from(series.values())}
function FinanceChart({series}:{series:{label:string;income:number;expense:number}[]}){const max=Math.max(...series.flatMap(item=>[item.income,item.expense]),1);return <div className="mt-6"><div className="flex h-48 items-end gap-2 border-b border-l border-[#E7E8EF] px-3 pb-0">{series.map(item=><div key={item.label} className="flex h-full flex-1 items-end justify-center gap-1"><div title={`Pemasukan ${currency.format(item.income)}`} className="w-3 rounded-t bg-[#5B4BFF]" style={{height:`${Math.max(item.income/max*100,item.income?3:0)}%`}}/><div title={`Pengeluaran ${currency.format(item.expense)}`} className="w-3 rounded-t bg-[#FF9A62]" style={{height:`${Math.max(item.expense/max*100,item.expense?3:0)}%`}}/></div>)}</div><div className="mt-2 flex gap-2 text-[10px] text-[#8D91A1]"><span className="h-2 w-2 rounded-full bg-[#5B4BFF]"/>Pemasukan<span className="ml-3 h-2 w-2 rounded-full bg-[#FF9A62]"/>Pengeluaran</div><div className="mt-1 flex justify-between pl-3 text-[10px] text-[#8D91A1]">{series.map(item=><span key={item.label}>{item.label}</span>)}</div></div>}
function Header({name}:{name:string}){return <header className="sticky top-0 z-10 flex min-h-[76px] flex-wrap items-center justify-between gap-x-5 gap-y-3 border-b border-[#E7E8EF] bg-white px-5 py-4 sm:px-10 lg:flex-nowrap lg:px-14"><Link href="/dashboard" className="flex shrink-0 items-center gap-3"><span className="flex h-[34px] w-[34px] items-center justify-center rounded-[9px] bg-[#5B4BFF] text-xs font-extrabold text-white">RW</span><span className="text-[17px] font-bold">Portal Warga</span></Link><nav className="order-3 flex w-full items-center gap-5 overflow-x-auto whitespace-nowrap text-[12px] font-medium text-[#6F7385] lg:order-none lg:w-auto lg:gap-7 lg:text-[13px]"><Link className="font-bold text-[#5B4BFF]" href="/dashboard">Beranda</Link><Link href="/informasi">Informasi</Link><Link href="/finance/reports">Keuangan</Link><Link href="/reports">Laporan Saya</Link><Link href="/reports/sick">Laporan Sakit</Link></nav><div className="flex shrink-0 items-center gap-3"><span className="hidden text-right sm:block"><strong className="block text-[13px]">{name}</strong><small className="text-[11px] text-[#6F7385]">Warga RW 08</small></span><span className="flex h-[38px] w-[38px] items-center justify-center rounded-full bg-[#D9D5FF] text-sm font-bold text-[#3728D6]">{name[0]}</span></div></header>}
function SectionHeader({title,link,linkLabel}:{title:string;link:string;linkLabel:string}){return <div className="flex items-center justify-between gap-3"><h2 className="text-xl font-bold">{title}</h2><Link href={link} className="shrink-0 text-xs font-bold text-[#5B4BFF]">{linkLabel} →</Link></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="py-8 text-center"><p className="text-sm font-bold text-[#111322]">{title}</p><p className="mt-2 text-xs leading-5 text-[#6F7385]">{text}</p></div>}
function PendingVerification(){return <main className="flex min-h-screen items-center justify-center bg-[#F5F6FA] px-5"><section className="w-full max-w-md rounded-[22px] bg-white p-8 text-center shadow-sm"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#EFEDFF] text-2xl text-[#5B4BFF]">✓</span><h1 className="mt-5 text-2xl font-bold">Akun menunggu verifikasi</h1><p className="mt-3 text-sm leading-6 text-[#6F7385]">Akun berhasil dibuat. Pengurus RW perlu memverifikasi akun sebelum dashboard dapat digunakan.</p></section></main>}
function Metric({label,value,color}:{label:string;value:number;color:string}){return <div className="rounded-2xl border border-[#E7E8EF] bg-white p-5"><p className="text-xs font-semibold text-[#6F7385]">{label}</p><p className={`mt-2 text-3xl font-bold ${color}`}>{value}</p></div>}
function Quick({href,icon,label}:{href:string;icon:string;label:string}){return <Link href={href} className="flex items-center gap-3 rounded-xl px-2 py-3 text-xs font-semibold text-[#111322] hover:bg-[#F5F6FA]"><span className="text-lg text-[#5B4BFF]">{icon}</span>{label}</Link>}
