'use client'

import { FormEvent, useEffect, useState } from 'react'

type Transaction = { id: string; type: string; paymentMethod: string; category: string; description: string; amount: string; occurredAt: string }
type Report = { id: string; title: string; status: string; periodStart: string; periodEnd: string }

export default function CmsFinancePage() {
  const [transactions, setTransactions] = useState<Transaction[]>([])
  const [reports, setReports] = useState<Report[]>([])
  const [form, setForm] = useState({ type: 'PEMASUKAN', paymentMethod: 'CASH', category: '', description: '', amount: '', occurredAt: '' })
  const [message, setMessage] = useState('')
  async function load() { const [t, r] = await Promise.all([fetch('/api/finance/transactions'), fetch('/api/finance/reports')]); if (t.ok) setTransactions((await t.json()).data); if (r.ok) setReports((await r.json()).data) }
  useEffect(() => { void load() }, [])
  async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch('/api/finance/transactions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, amount: Number(form.amount), occurredAt: new Date(form.occurredAt).toISOString() }) }); const result = await response.json(); setMessage(response.ok ? 'Transaksi tersimpan.' : result.error ?? 'Gagal menyimpan transaksi.'); if (response.ok) { setForm({ type: 'PEMASUKAN', paymentMethod: 'CASH', category: '', description: '', amount: '', occurredAt: '' }); await load() } }
  return <main className="min-h-screen bg-[#f7f7fb] px-5 py-10"><section className="mx-auto max-w-6xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#5b4bff]">CMS Pengurus</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Keuangan RW</h1><div className="mt-8 grid gap-6 lg:grid-cols-[380px_1fr]"><form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Catat transaksi</h2><div className="mt-5 space-y-4"><select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })} className="h-12 w-full rounded-xl border px-4 text-sm"><option value="PEMASUKAN">Pemasukan</option><option value="PENGELUARAN">Pengeluaran</option></select><select value={form.paymentMethod} onChange={e => setForm({ ...form, paymentMethod: e.target.value })} className="h-12 w-full rounded-xl border px-4 text-sm"><option value="CASH">Cash</option><option value="TRANSFER">Transfer</option></select><input required placeholder="Kategori" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} className="h-12 w-full rounded-xl border px-4 text-sm" /><input required placeholder="Nominal" type="number" min="1" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} className="h-12 w-full rounded-xl border px-4 text-sm" /><input required type="datetime-local" value={form.occurredAt} onChange={e => setForm({ ...form, occurredAt: e.target.value })} className="h-12 w-full rounded-xl border px-4 text-sm" /><textarea required placeholder="Deskripsi" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="min-h-24 w-full rounded-xl border p-4 text-sm" />{message && <p className="text-sm text-slate-600">{message}</p>}<button className="h-12 w-full rounded-xl bg-[#5b4bff] text-sm font-bold text-white">Simpan transaksi</button></div></form><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Transaksi terbaru</h2><div className="mt-5 space-y-3">{transactions.map(t => <article key={t.id} className="flex justify-between gap-4 rounded-2xl border p-4"><div><p className="font-bold">{t.category}</p><p className="text-sm text-slate-500">{t.description} · {t.paymentMethod}</p></div><p className={t.type === 'PEMASUKAN' ? 'font-bold text-emerald-600' : 'font-bold text-red-600'}>{t.type === 'PEMASUKAN' ? '+' : '-'} Rp {Number(t.amount).toLocaleString('id-ID')}</p></article>)}</div><h2 className="mt-8 text-lg font-bold">Laporan keuangan</h2><div className="mt-4 space-y-3">{reports.map(r => <article key={r.id} className="rounded-2xl border p-4"><div className="flex justify-between"><p className="font-bold">{r.title}</p><span className="text-xs font-semibold">{r.status}</span></div></article>)}</div></section></div></section></main>
}
